### ISSUE TITLE
colorized_totals_line bug

### ISSUE THREAD

**Issue by dillonhafer** [briandunn/flatware#36]
Ruby Version: 2.2.3
Flatware: 839616cdb159

rspec runs all the tests fine, but crashes when trying to display the results. This error is triggered by running `flatware rspec` against the entire suite, or just a directory, or just a single file.

```
/gems/rspec-core-3.6.0/lib/rspec/core/notifications.rb:339:in `colorized_totals_line': undefined method `>' for nil:NilClass (NoMethodError)
from /gems/rspec-core-3.6.0/lib/rspec/core/notifications.rb:380:in `fully_formatted'
from /bundler/gems/flatware-839616cdb159/lib/flatware/rspec/summary.rb:24:in `fully_formatted'
from /gems/rspec-core-3.6.0/lib/rspec/core/formatters/base_text_formatter.rb:43:in `dump_summary'
from /bundler/gems/flatware-839616cdb159/lib/flatware/rspec/formatters/console.rb:19:in `summarize'
from /bundler/gems/flatware-839616cdb159/lib/flatware/broadcaster.rb:11:in `block in method_missing'
from /bundler/gems/flatware-839616cdb159/lib/flatware/broadcaster.rb:10:in `each'
from /bundler/gems/flatware-839616cdb159/lib/flatware/broadcaster.rb:10:in `method_missing'
from /bundler/gems/flatware-839616cdb159/lib/flatware/sink.rb:65:in `listen'
from /bundler/gems/flatware-839616cdb159/lib/flatware/sink.rb:35:in `start'
from /bundler/gems/flatware-839616cdb159/lib/flatware/sink.rb:7:in `start_server'
from /bundler/gems/flatware-839616cdb159/lib/flatware/cli.rb:44:in `start_sink'
from /bundler/gems/flatware-839616cdb159/lib/flatware/rspec/cli.rb:13:in `rspec'
from /gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
from /gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
from /gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
from /gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
from /bundler/gems/flatware-839616cdb159/bin/flatware:6:in `<top (required)>'
from /bin/flatware:23:in `load'
from /bin/flatware:23:in `<main>'
from /bin/ruby_executable_hooks:15:in `eval'
from /bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dillonhafer** [comment]
Thanks for fixing this! ❤️
