### ISSUE TITLE
Require 'set'

### ISSUE THREAD

**Issue by jhottenstein** [briandunn/flatware#64]
I can't repro in the test directory but in my rails app i get: 
```
$ bin/flatware rspec
/Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-2.0.0/lib/flatware/sink.rb:29:in `initialize': uninitialized constant Flatware::Sink::Server::Set (NameError)
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-2.0.0/lib/flatware/sink.rb:8:in `new'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-2.0.0/lib/flatware/sink.rb:8:in `start_server'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-2.0.0/lib/flatware/cli.rb:59:in `start_sink'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-rspec-2.0.0/lib/flatware/rspec/cli.rb:27:in `rspec'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/jess/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/flatware-2.0.0/bin/flatware:6:in `<top (required)>'
	from bin/flatware:29:in `load'
	from bin/flatware:29:in `<main>'
```

I think the simple fix is to ensure we `require 'set'` in files that refer to it.

**Comment by briandunn** [comment]
thanks for the fix @jhottenstein
